# Generated by Django 4.0.5 on 2022-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACKS', 'Snacks')], max_length=10)),
                ('Red_Meat', models.IntegerField()),
                ('Fish_Chicken_Eggs', models.IntegerField()),
                ('Nuts_Seeds_Beans_Tofu', models.IntegerField()),
                ('Dairy', models.IntegerField()),
                ('Vegetable', models.IntegerField()),
                ('Fruits', models.IntegerField()),
                ('Healthy_Fats_Oils', models.IntegerField()),
                ('Whole_Grains', models.IntegerField()),
                ('Sugary_Treats', models.IntegerField()),
                ('Salty_Treats', models.IntegerField()),
                ('Wheat_Flour_Corn_Treats', models.IntegerField()),
                ('Alcohol', models.IntegerField()),
            ],
            options={
                'ordering': ['dish'],
            },
        ),
    ]
