# Generated by Django 4.0.5 on 2022-06-08 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile_favorite_food_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
